<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,2,1,'5Lqn5ZOB');
$cfg_Cs[2]=array(0,1,1,'5Yqo5oCB');
$cfg_Cs[3]=array(0,1,1,'5pyN5Yqh');
$cfg_Cs[4]=array(0,1,1,'5YWz5LqO');
$cfg_Cs[5]=array(0,1,1,'5qGI5L6L');
$cfg_Cs[6]=array(5,1,1,'5a2m5qCh6aWu5rC0');
$cfg_Cs[7]=array(5,1,1,'5Lit5aSu5Yi25rC06K6+5aSH');
$cfg_Cs[8]=array(5,1,1,'5rip54Ot5LiA5L2T5py6');
$cfg_Cs[9]=array(5,1,1,'5q2l6L+b5byP6aWu5rC05bmz5Y+w');
$cfg_Cs[10]=array(1,2,1,'5rip5o6n566h57q/5py6');
$cfg_Cs[11]=array(1,2,1,'5Lit5aSu5rK75rC06K6+5aSH');
$cfg_Cs[12]=array(1,2,1,'5rip54Ot5LiA5L2T5py6');
$cfg_Cs[13]=array(1,2,1,'5q2l6L+b5byP6aWu5rC05bmz5Y+w');
$cfg_Cs[14]=array(0,17,0,'6aaW6aG16L2u5pKt5Zu+');
?>