<div class="case-list wrap">
        {dede:arclist titlelen='42' row='1'}

            <div class="content-left">
                <h2>[field:title /]</h2>
                <p>[field:description/]</p>
                <a href="[field:arcurl /]"> <p>More...</p> </a>
            </div>
            <div class="content-right wow bounceInLeft bg-green">
                <img src="{dede:global.cfg_templets_skin/}/img/company.png" />
            </div>
        </a>
        {/dede:arclist}
    </div>