<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:eding itemname="额定功率" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="220V"  maxlength="250" page="">
</field:eding>
<field:edpl itemname="额定频率" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="50HZ"  maxlength="250" page="">
</field:edpl>
<field:stsy itemname="渗透水压" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="0.1-0.3VPA"  maxlength="250" page="">
</field:stsy>
