<?php
$z[0]=Array("arclist","\r\n\r\n            <div class=\"content-left\">\r\n                <h2>[field:title /]</h2>\r\n                <p>[field:description/]</p>\r\n                <a href=\"[field:arcurl /]\"> <p>More...</p> </a>\r\n            </div>\r\n            <div class=\"content-right\">\r\n                <img src=\"[field:litpic/]\" />\r\n            </div>\r\n        </a>\r\n        ",44,441);
$z[0][4]['titlelen']="42";
$z[0][4]['row']="1";

?>