<?php
$z[0]=Array("arclist","\r\n\r\n            <div class=\"content-left\">\r\n                <h2>[field:title /]</h2>\r\n                <p>[field:description/]</p>\r\n                <a href=\"href=\"[field:arcurl /]\"\"> <p>More...</p> </a>\r\n            </div>\r\n            <div class=\"content-right wow bounceInLeft bg-green\">\r\n                <img src=\"{dede:global.cfg_templets_skin/}/img/company.png\" />\r\n            </div>\r\n        </a>\r\n        ",38,501);
$z[0][4]['titlelen']="42";
$z[0][4]['row']="1";

?>