<?php
$z[0]=Array("channel","\r\n    <div class=\"case-list wrap none\" >\r\n\r\n\r\n            <div class=\"content-left\">\r\n                <h2>[field:title /]</h2>\r\n                <p>[field:description/]</p>\r\n                <a href=\"[field:arcurl /]\"> <p>More...</p> </a>\r\n            </div>\r\n            <div class=\"content-right\">\r\n                <img src=\"[field:litpic/]\" />\r\n            </div>\r\n        </a>\r\n        \r\n    </div>\r\n    ",0,460);
$z[0][4]['type']="son";
$z[0][4]['noself']="yes";

?>