{dede:arclist titlelen='42' row='5' type='son'}
    <div class="case-list wrap none" >


            <div class="content-left">
                <h2>[field:title /]</h2>
                <p>[field:description/]</p>
                <a href="[field:arcurl /]"> <p>More...</p> </a>
            </div>
            <div class="content-right">
                <img src="[field:litpic/]" />
            </div>
        </a>

    </div>
    {/dede:arclist}