<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",133,152);
$z[1][4]['name']="title";
$z[2]=Array("field","",170,226);
$z[2][4]['name']="pubdate";
$z[2][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[3]=Array("field","",268,295);
$z[3][4]['name']="phpurl";
$z[4]=Array("field","",319,342);
$z[4][4]['name']="id";
$z[5]=Array("field","",347,371);
$z[5][4]['name']="mid";
$z[6]=Array("field","",509,527);
$z[6][4]['name']="body";
$z[7]=Array("include","",575,612);
$z[7][4]['filename']="footer.htm";

?>