<?php
$z[0]=Array("global","",74,100);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",101,120);
$z[1][4]['name']="title";
$z[2]=Array("global","",168,198);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",239,266);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",321,353);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",413,445);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",520,552);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",591,623);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",774,806);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",916,941);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("field","(@me==\"\")? @me=\" class='acti'\":@me=\"\";",944,1032);
$z[10][4]['name']="typeid";
$z[10][4]['runphp']="yes";
$z[11]=Array("channel","\r\n                <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n            ",1076,1320);
$z[11][4]['type']="top";
$z[11][4]['row']="10";
$z[11][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~ class='acti'>~typename~</a></li>";

?>