<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","(@me==\"\")? @me=\" class='acti'\":@me=\"\";",171,261);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n                    <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",317,527);
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li class=\"acti\"><a href=\"~typelink~\">~typename~</a></li>";
$z[3]=Array("list","\r\n            <a href=\"[field:arcurl/]\">\r\n            <div class=\"single\">\r\n                <img src=\"[field:litpic/]\">\r\n                <div class=\"beijing\">\r\n                    [field:title/]\r\n                </div>\r\n            </div>\r\n\r\n            ",730,1020);
$z[3][4]['pagesize']="8";
$z[4]=Array("pagelist","",1148,1204);
$z[4][4]['listitem']="pre,next,pageno";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",1247,1284);
$z[5][4]['filename']="footer.htm";

?>