<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",69,101);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("list","\r\n        <a href=\"[field:arcurl/]\">\r\n            <div class=\"single\">\r\n                <img src=\"[field:litpic/]\">\r\n                <div class=\"news_content\">\r\n                    <h2>[field:title/]</h2>\r\n                    <p class=\"content-text\">[field:description/]</p>\r\n                    <p>[field:pubdate function=\"GetDateTimeMK(@me)\"/] </p>\r\n                </div>\r\n            </div>\r\n        </a>\r\n        ",229,683);
$z[2][4]['pagesize']="8";
$z[3]=Array("pagelist","",793,849);
$z[3][4]['listitem']="pre,next,pageno";
$z[3][4]['listsize']="5";
$z[4]=Array("include","",914,951);
$z[4][4]['filename']="footer.htm";

?>